services:
  # A Docker web service
  - type: web
    name: Video-Encoder-BOT
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/erotixe/Video-Encoder-BOT.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: stream-feature # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /

#End of yaml
